import { knightMoves } from "./knightMoves.js";

console.log("Test Case 1: ", knightMoves([0, 0], [1, 2]));
console.log("------------------------------------------");
console.log("Test Case 2: ", knightMoves([0, 0], [3, 3]));
console.log("------------------------------------------");
console.log("Test Case 3: ", knightMoves([3, 3], [0, 0]));
console.log("------------------------------------------");
console.log("Test Case 4: ", knightMoves([0, 0], [7, 7]));
console.log("------------------------------------------");
console.log("Test Case 5: ", knightMoves([0, 0], [4, 5]));
console.log("------------------------------------------");
console.log("Test Case 6: ", knightMoves([7, 7], [0, 0]));
console.log("------------------------------------------");
console.log("Test Case 7: ", knightMoves([2, 2], [5, 5]));
console.log("------------------------------------------");
console.log("Test Case 8: ", knightMoves([6, 6], [7, 7]));
console.log("------------------------------------------");
console.log("Test Case 9: ", knightMoves([0, 0], [0, 0]));
console.log("------------------------------------------");
console.log("Test Case 10: ", knightMoves([1, 1], [2, 3]));
console.log("------------------------------------------");
console.log("Test Case 11: ", knightMoves([0, 0], [0, 1]));
console.log("------------------------------------------");
console.log("Test Case 12: ", knightMoves([-1, -1], [0, 0]));
console.log("------------------------------------------");
console.log("Test Case 13: ", knightMoves([-1, 0], [0, 0]));
console.log("------------------------------------------");
console.log("Test Case 14: ", knightMoves([0, -1], [0, 0]));
console.log("------------------------------------------");
console.log("Test Case 15: ", knightMoves([0, 0], [-1, 0]));
console.log("------------------------------------------");
console.log("Test Case 16: ", knightMoves([0, 0], [8, 0]));
